### ISSUE TITLE
Exclude Users should by implemented in the installation Script

### ISSUE THREAD

**Issue by githubths** [Kili69/Tier0-User-Management#1]
Hi Lucas,

Install-T0.ps1 
should also include the excludeUser parameter to exclude multiple BreakGlas admins during installation.

Tier0UserManagement.ps1 
Old  -> [string]$ExcludeUser,
new -> [string[]]$ExcludeUser,
the Parameter excludeUser should by a String Array to exclude multiple User DNs.
the excludeUser should also by excluded on the Authentication Policy

Kind Regards.

**Comment by Kili69** [comment]
Hi Stefan, 

good idea 👍
