### ISSUE TITLE
Memberof Check not successfull

### ISSUE THREAD

**Issue by githubths** [Kili69/Tier0-User-Management#2]
Tier0UserManagement.ps1
if ($user.memberOf -notcontains $Tier0UsersGroup.DistinguishedName){
the Vairable $Tier0UsersGroup is never by populated

https://github.com/Kili69/Tier0-User-Management/blame/de8f378f0a6aa29d5a77c54d7f1c05114e980497/Tier0UserManagement.ps1#L197

**Comment by Kili69** [comment]
Hi Stefan, 
the Tier 0 users group check is not used anymore. I will removed the code in the next version, With authentication policies it is not required to add all Tier 0 users into a group

**Comment by githubths** [comment]
Thanks. It is a pity that no group can be specified in the authentication policies.
